site_name: Modern Graphics Engine Guide
docs_dir: Docs
repo_url: https://github.com/Italink/ModernGraphicsEngineGuide
repo_name: Github
nav:
    - '开篇' : 'README.md'
    - C++:
        - '计算机发展史': '00-C++/1.计算机发展史.md'
        - 'C++学习路线': '00-C++/2.C++学习路线.md'
        - '现代开发工作流': '00-C++/3.现代开发工作流.md'
        - '库': '00-C++/4.库.md'
        - '宏、模板、反射': '00-C++/5.宏、模板、反射.md'
        - '内存管理、跨平台': '00-C++/6.内存管理、跨平台.md'
    - GUI:
        - "窗口基础" : "01-GUI/0.窗口基础.md"
        - "Qt" : "01-GUI/1.Qt.md"
        - "ImGUI" : "01-GUI/2.ImGUI.md"
    - '现代图形API':
        - '窗口和部件':  "02-Graphics/0.WindowAndWidget.md"
theme:
    icon:
        repo: fontawesome/brands/github
    language: zh
    name: material
    features:
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
plugins:
    - search:
        lang: 
            - en
            - zh
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
markdown_extensions:
    - abbr
    - admonition
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: 这篇文章对你有用吗？
      ratings:
        - icon: material/thumb-up-outline
          name: 这是一篇有用的文章
          data: 1
          note: >-
            感谢你的认可0.0
        - icon: material/thumb-down-outline
          name: 这篇文章中有问题
          data: 0
          note: >- 
            感谢你的反馈
            请在<a href="https://github.com/Italink/ModernGraphicsEngineGuide/issues/new" target="_blank" rel="noopener">Github Issue</a>上简述问题
            博主将尽快修复
extra_css:
  - Stylesheet/mkdocs_extra.css

